{
  "_args": [
    [
      {
        "raw": "async-timeout",
        "scope": null,
        "escapedName": "async-timeout",
        "name": "async-timeout",
        "rawSpec": "",
        "spec": "latest",
        "type": "tag"
      },
      "C:\\Users\\jujha\\Documents\\GitHub\\Coolio"
    ]
  ],
  "_from": "async-timeout@latest",
  "_id": "async-timeout@1.0.2",
  "_inCache": true,
  "_location": "/async-timeout",
  "_npmUser": {
    "name": "ifroz",
    "email": "ifrozen@gmail.com"
  },
  "_npmVersion": "2.0.0",
  "_phantomChildren": {},
  "_requested": {
    "raw": "async-timeout",
    "scope": null,
    "escapedName": "async-timeout",
    "name": "async-timeout",
    "rawSpec": "",
    "spec": "latest",
    "type": "tag"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/async-timeout/-/async-timeout-1.0.2.tgz",
  "_shasum": "7cb54ebc2450acfb85a0415b37a817b0e5548511",
  "_shrinkwrap": null,
  "_spec": "async-timeout",
  "_where": "C:\\Users\\jujha\\Documents\\GitHub\\Coolio",
  "author": {
    "name": "Laci Szucs",
    "email": "ifrozen@gmail.com"
  },
  "dependencies": {},
  "description": "async-timeout is a simple async task wrapper which triggers the callback. It supresses errors (by default), thus uses the timeout fallbacks also as an error fallback.",
  "devDependencies": {},
  "directories": {},
  "dist": {
    "shasum": "7cb54ebc2450acfb85a0415b37a817b0e5548511",
    "tarball": "https://registry.npmjs.org/async-timeout/-/async-timeout-1.0.2.tgz"
  },
  "gitHead": "a4278e834a31472c2e81a0d803c8898869b3caa9",
  "keywords": [
    "async",
    "timeout",
    "setTimeout"
  ],
  "license": "ISC",
  "main": "async-timeout.js",
  "maintainers": [
    {
      "name": "ifroz",
      "email": "ifrozen@gmail.com"
    }
  ],
  "name": "async-timeout",
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "version": "1.0.2"
}
